##Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_math =[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.82064114, 0.28014991, 0.45345305, 0.50431949, 0.57008528])

In [21]:
np.random.rand(5,5)

array([[0.83557803, 0.27312377, 0.59818367, 0.6455734 , 0.98475904],
       [0.64799985, 0.85781735, 0.90192825, 0.37072016, 0.80450999],
       [0.48502049, 0.05449218, 0.97469482, 0.56567141, 0.58467014],
       [0.3667306 , 0.55099979, 0.59984   , 0.74106316, 0.49722631],
       [0.79980842, 0.14240746, 0.37790448, 0.01097566, 0.74883404]])

In [22]:
np.random.randn(5)

array([-0.34527232,  1.2595686 ,  0.38439765, -0.14666035,  2.16195778])

In [24]:
np.random.randint(5,100)

95

In [26]:
 arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([12, 35, 36, 20,  6, 44,  3, 37, 46, 46], dtype=int32)

In [33]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

np.int32(46)

In [39]:
ranarr.min()

np.int32(3)

In [37]:
ranarr.argmax()

np.int64(8)

In [42]:
ranarr.argmin()

np.int64(6)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.dtype

dtype('int64')

In [46]:
arr.shape

(5, 5)

In [49]:
from numpy.random import randint

In [51]:
randint(2,10)

9