In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

np.int64(8)

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [23]:
arr_copy[:] = 100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## NumPy Indexing and Selection

In [26]:
import numpy as np

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0][0]

np.int64(5)

In [31]:
arr_2d[0]

array([ 5, 10, 15])

In [32]:
arr_2d[1][1]

np.int64(25)

In [33]:
arr_2d[2][1]

np.int64(40)

In [35]:
arr_2d[1,2]

np.int64(30)

In [36]:
arr_2d[1][2]

np.int64(30)

In [38]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [40]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
boo_arr = arr > 5

In [44]:
boo_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
arr[boo_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr<5]

array([1, 2, 3, 4])

In [48]:
arr[arr<3]

array([1, 2])